image: eclipse-temurin:17-jdk-alpine

stages:
  - build_and_test

build_job:
  only:
    - main
  stage: build_and_test
  script:
    - java -version
    - ./gradlew build
    - ./gradlew test
    - ./gradlew jar
    - ./gradlew publish # to mavenLocal
